# Numpy
NumPy è indispensabile per il calcolo numerico ed è alla base di molte librerie come Pandas, Scikit-Learn e TensorFlow. I suoi vantaggi principali sono: 
- Velocità (ottimizzato in C)
- Efficienza (operazioni su array senza loop)
- Versatilità (statistiche, algebra lineare, gestione di grandi dataset)


In [4]:
# import
import numpy as np

## Creare oggetti numpy

In [9]:
# creazione di un array
a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


In [122]:
print(type(a))

<class 'numpy.ndarray'>


In [13]:
# creazione di un array di zeri in particolare, Francesco, crea una lista di 5 zeri 
b = np.zeros(5)
print(b)

[0. 0. 0. 0. 0.]


In [15]:
# creazione di un array di uno
c = np.ones(5)
print(c)

[1. 1. 1. 1. 1.]


In [25]:
# creazione di un range di valori
d = np.arange(10)
print(d)

[0 1 2 3 4 5 6 7 8 9]


In [40]:
# creazione di un array di valori casuali compresi tra 0 e 1
e = np.random.rand(3)
print(e)

[0.95300369 0.77262031 0.60170769]


In [55]:
# creazione di un array di valori interi casuali compresi tra 10 e 20
f = np.random.randint(10, 20, 5) 
print(f)

[13 10 18 13 15]


In [56]:
# creazione di una matrice
g = np.array([[1, 2, 3], [4, 5, 6]])
print(g)

[[1 2 3]
 [4 5 6]]


In [61]:
g.flatten()

array([1, 2, 3, 4, 5, 6])

In [60]:
zer = np.zeros(3)
ones = np.ones(3)

one_zero = np.array([zer, ones])
print(one_zero)

[[0. 0. 0.]
 [1. 1. 1.]]


## Operazioni

In [62]:
# + per le liste
l1 = [1, 2, 3]
l2 = [4, 5, 6]
print(l1 + l2)

[1, 2, 3, 4, 5, 6]


In [63]:
# + per gli array
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])
print(a1 + a2)

[5 7 9]


In [64]:
# * per le liste
l1 = [1, 2, 3]
print(l1 * 3)

[1, 2, 3, 1, 2, 3, 1, 2, 3]


In [65]:
# * per gli array
a1 = np.array([1, 2, 3])
print(a1 * 3)

[3 6 9]


In [71]:
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])
print(a1 * a2)


[ 4 10 18]


In [72]:
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])
print(a1 ** a2)


[  1  32 729]


In [74]:
a1 = np.array([1, 4, 5])
print(np.sqrt(a1)) # sqrt = square root

[1.         2.         2.23606798]


In [75]:
# radice cubica
a = np.array([1, 8, 27])
print(np.cbrt(a))

[1. 2. 3.]


## Statistiche

In [76]:
a = np.array([1, 2, 3])
print(np.mean(a)) # mean = media

2.0


In [107]:
a = np.array([1, 2, 5, 10])
print(np.median(a)) # mediana

3.5


In [108]:
result = np.sum(a)
print(result)

18


In [109]:
result = np.prod(a)
print(result)

100


In [110]:
result = np.diff(a)
print(result)

[1 3 5]


In [111]:
result = np.std(a)
print(result)

3.5


In [118]:
a = np.array([1, 1, 2, -1, 3, 2])
print(a.std())

1.247219128924647


In [116]:
print(np.min(a))
print(np.max(a))

1
2


In [120]:
print(np.argmax(a))

4


In [121]:
print(np.unique(a))

[-1  1  2  3]


In [81]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [93]:
a > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [94]:
result = a[(a > 5) & (a < 8) & (a % 2 == 0)]
print(result)

[6]


In [102]:
cond1 = a > 5
cond2 = a < 8
result = a[cond1 & cond2]
print(result)

[6 7]


In [90]:
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [91]:
print(a[a < 5])

[0 1 2 3 4]


In [103]:
cond1 = a > 1 # return a boolean array
cond2 = a < 9 # return a boolean array
print(a[cond1 & cond2])

[2 3 4 5 6 7 8]
